# Lecture 1
## Numerical Arrays and Vectorised Computation

### Setup
Run next cell to install library used in examples.

In [2]:
!pip install -U --no-cache https://github.com/johnhw/jhwutils/zipball/master

In [3]:
# various imports we will need
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

import jhwutils.image_audio as image_audio
from jhwutils.image_audio import (
    play_sound,
    show_image,
    load_image_colour,
    load_image_gray,
    show_image_mpl,
    load_sound,
    play_sound,
)
from jhwutils.matrices import show_boxed_tensor_latex, print_matrix

%matplotlib inline
plt.rc("figure", figsize=(14.0, 7.0))

C:\Users\andre\anaconda3\lib\site-packages\IPython\kernel\__init__.py:12: ShimWarning: The `IPython.kernel` package has been deprecated since IPython 4.0.You should import from ipykernel or jupyter_client instead.
  warn("The `IPython.kernel` package has been deprecated since IPython 4.0."


### Topics covered in Lecture 1:
* N-Dimensional Arrays (ndarrays)
* Vectorised Computation
    * Vector
    * Matrix
    * Tensor

## N-Dimensional Arrays

### What is an N-Dimensional Array?

An N-Dimensional Array (ndarray) is a container of items of the same type and size.

It has a 'shape' which defines its number of dimensions and items.

It also has a 'dtype' which specifies the data type of objects in the ndarray.


In [4]:
x = np.array([1,2,3], np.int32)

print(x, x.dtype, x.shape)

[1 2 3] int32 (3,)


## Vectorisation

### What is Vectorised Computation?

Writing code that acts on arrays of values simultaneously.

### Vectors, Matrix and Tensors


A 'Vector' is a one-dimensional (1D) array of values:

In [16]:
vector = [0,1,2,3,4,5]

A 'Matrix' is a two-dimensional (2D) array of values with rows and columns:

In [17]:
matrix = [[1,2,3],
         [4,5,6],
         [7,8,9]]

A 'Tensor' is an array with more than two dimensions - more often known as an N-Dimensional Array (ndarray):

In [18]:
tensor = [[[1,2,3],
         [4,5,6],
         [7,8,9]],
          
         [[10,11,12],
         [13,14,15],
         [16,17,18]]]

## Array Operations

There are many different operations that can be performed on arrays. Here are some examples:

### Slice

Used to 'slice' out segments of the array.

In [11]:
complete_array = np.array([100,200,300,400,500])

sliced_array = complete_array[0:3]

print(sliced_array)

[100 200 300]


### Filter

Filters results on matching criteria.

In [13]:
matching_elements = complete_array[complete_array > 300]

print(matching_elements)

[400 500]


### Reduce

Reduce aggregates across dimensions of an array.

What is the 'axis' for?

In [14]:
weights = np.array([[5,6,7],
                  [5,6,7],
                  [5,6,7]])

np.sum(weights, axis=0)

array([15, 18, 21])